config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "ask", to: "questions#ask", as: :ask
  get "answer", to: "questions#answer", as: :answer
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask
  end

  def answer
  @question = params[:question]
  if @question[(@question.length - 1)] == "?"
    @answer = "Silly question, get dressed and go to work!"
  elsif @question.downcase == "I am going to work right now!".downcase
    @answer = "Great!"
  else
    @answer = "I don't care, get dressed and go to work!"
  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Stupid Coaching!</h1>

<div class="question">
<h3>- <%= params[:question] %></h3>
<h5>- You</h5>
</div>

<div class= "answer">
<h3>- <%= @answer %></h3>
  <h5>- Your coach</h5>
</div>

<%= link_to "Ask a new question", ask_path %>

app/views/questions/ask.html.erb
<p>Ask your coach anything:</p>
<form action="/answer">
  <input type="text" name="question" placeholder="What is your question?">
  <input type="submit" value="Ask!">
</form>